### ISSUE TITLE
coolstars19.com domain retiring soon

### ISSUE THREAD

**Issue by astro-alexis** [CoolStars20/CoolStars20.github.io#1]
Hello,

The coolstars19.com domain will be retired very soon. It was only a redirection to the actual CS19 webpage URL hosted on our servers in Uppsala at https://www.astro.uu.se/~cool19/

Could you replace **coolstars19.com** by **https://www.astro.uu.se/~cool19** in index.html for longevity purposes :)? Maybe also on CS20.5 website?

Thanks!
Alexis

**Comment by hamogu** [comment]
Done on the live website (by hand). I'll update the repro next in case someone ever decides to clone this again.
